### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by staticfloat** [dmbates/FLAC.jl#6]
Once you're satisfied that this is useful for others, it'd be nice to cut a release so others can get this without having to explicitly `Pkg.clone()` it.

**Comment by dmbates** [comment]
I'm in git hell again and can't publish a package.  It's the usual "can't do this until you do that" and "can't do that until you do this" series of instructions from git.  

If I abandon the Julia language it will be because I can't work with git.

@staticfloat If I add you as a contributor on this repository can you cut a release?

**Comment by staticfloat** [comment]
Sure thing.  If you tell me what the problems with `git` are, I may be able to help walk you through fixing that as well.

**Comment by staticfloat** [comment]
Ah, you made me a contributor already, so I will just enable Travis testing and then cut the release.

**Comment by staticfloat** [comment]
Release complete in https://github.com/JuliaLang/METADATA.jl/pull/5027

**Comment by tkelman** [comment]
please do enable travis
